CRITICAL - 2023-05-11 12:29:24 --> Undefined variable $auth_user
in APPPATH\Views\auth_users\editar.php on line 14.
 1 APPPATH\Views\auth_users\editar.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $auth_user', 'C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\auth_users\\editar.php', 14)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\auth_users\\editar.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth_users/editar', [], true)
 5 APPPATH\Controllers\AuthUsers.php(29): view('auth_users/editar')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthUsers->editar('1')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 12:34:10 --> Too few arguments to function App\Controllers\AuthUsers::editar(), 0 passed in C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php on line 934 and exactly 1 expected
in APPPATH\Controllers\AuthUsers.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthUsers->editar()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 12:36:33 --> Too few arguments to function App\Controllers\AuthUsers::editar(), 0 passed in C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php on line 934 and exactly 1 expected
in APPPATH\Controllers\AuthUsers.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthUsers->editar()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 12:36:57 --> Too few arguments to function App\Controllers\AuthUsers::editar(), 0 passed in C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php on line 934 and exactly 1 expected
in APPPATH\Controllers\AuthUsers.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthUsers->editar()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 12:38:31 --> Too few arguments to function App\Controllers\AuthUsers::editar(), 0 passed in C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php on line 934 and exactly 1 expected
in APPPATH\Controllers\AuthUsers.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthUsers->editar()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 13:01:05 --> link(): No such file or directory
in APPPATH\Controllers\Home.php on line 10.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'link(): No such file or directory', 'C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Controllers\\Home.php', 10)
 2 APPPATH\Controllers\Home.php(10): link('/AuthUsers/index', 'Auth_users')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 15:10:05 --> Too few arguments to function App\Controllers\AuthUsers::ver(), 0 passed in C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php on line 934 and exactly 1 expected
in APPPATH\Controllers\AuthUsers.php on line 51.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthUsers->ver()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-11 17:13:40 --> mysqli_sql_exception: Duplicate entry '5' for key 'PRIMARY' in C:\xampp\htdocs\pesquisa_satisfacao\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\pesquisa_satisfacao\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `au...', 0)
#1 C:\xampp\htdocs\pesquisa_satisfacao\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `au...')
#2 C:\xampp\htdocs\pesquisa_satisfacao\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `au...')
#3 C:\xampp\htdocs\pesquisa_satisfacao\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `au...', Array, false)
#4 C:\xampp\htdocs\pesquisa_satisfacao\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pesquisa_satisfacao\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pesquisa_satisfacao\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\pesquisa_satisfacao\app\Controllers\AuthUsers.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php(934): App\Controllers\AuthUsers->store()
#9 C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
#10 C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\pesquisa_satisfacao\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-11 17:13:40 --> Duplicate entry '5' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `auth_users` (`nome`, `id_user`, `created_at`, `updated_at`) VALUES (\'Esdras\', \'5\', \'2023-05-11 17:13:40\', \'2023-05-11 17:13:40\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `auth_users` (`nome`, `id_user`, `created_at`, `updated_at`) VALUES (\'Esdras\', \'5\', \'2023-05-11 17:13:40\', \'2023-05-11 17:13:40\')')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `auth_users` (`nome`, `id_user`, `created_at`, `updated_at`) VALUES (\'Esdras\', \'5\', \'2023-05-11 17:13:40\', \'2023-05-11 17:13:40\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `auth_users` (`nome`, `id_user`, `created_at`, `updated_at`) VALUES (:nome:, :id_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AuthUsers.php(41): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthUsers->store()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-11 17:14:07 --> mysqli_sql_exception: Duplicate entry '5' for key 'PRIMARY' in C:\xampp\htdocs\pesquisa_satisfacao\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\pesquisa_satisfacao\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `au...', 0)
#1 C:\xampp\htdocs\pesquisa_satisfacao\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `au...')
#2 C:\xampp\htdocs\pesquisa_satisfacao\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `au...')
#3 C:\xampp\htdocs\pesquisa_satisfacao\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `au...', Array, false)
#4 C:\xampp\htdocs\pesquisa_satisfacao\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pesquisa_satisfacao\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pesquisa_satisfacao\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\pesquisa_satisfacao\app\Controllers\AuthUsers.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php(934): App\Controllers\AuthUsers->store()
#9 C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
#10 C:\xampp\htdocs\pesquisa_satisfacao\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\pesquisa_satisfacao\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-11 17:14:07 --> Duplicate entry '5' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `auth_users` (`nome`, `id_user`, `created_at`, `updated_at`) VALUES (\'Esdras\', \'5\', \'2023-05-11 17:14:07\', \'2023-05-11 17:14:07\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `auth_users` (`nome`, `id_user`, `created_at`, `updated_at`) VALUES (\'Esdras\', \'5\', \'2023-05-11 17:14:07\', \'2023-05-11 17:14:07\')')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `auth_users` (`nome`, `id_user`, `created_at`, `updated_at`) VALUES (\'Esdras\', \'5\', \'2023-05-11 17:14:07\', \'2023-05-11 17:14:07\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `auth_users` (`nome`, `id_user`, `created_at`, `updated_at`) VALUES (:nome:, :id_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\AuthUsers.php(41): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthUsers->store()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthUsers))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 17:30:18 --> Undefined variable $autpesquisah_user
in APPPATH\Views\pesquisas\index.php on line 25.
 1 APPPATH\Views\pesquisas\index.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $autpesquisah_user', 'C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\pesquisas\\index.php', 25)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\pesquisas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('pesquisas/index', [], true)
 5 APPPATH\Controllers\Pesquisas.php(22): view('pesquisas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pesquisas->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pesquisas))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 17:30:32 --> Undefined array key "id_user"
in APPPATH\Views\pesquisas\index.php on line 29.
 1 APPPATH\Views\pesquisas\index.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id_user"', 'C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\pesquisas\\index.php', 29)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\pesquisas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('pesquisas/index', [], true)
 5 APPPATH\Controllers\Pesquisas.php(22): view('pesquisas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pesquisas->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pesquisas))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 17:30:40 --> Undefined array key "id_user"
in APPPATH\Views\pesquisas\index.php on line 29.
 1 APPPATH\Views\pesquisas\index.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id_user"', 'C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\pesquisas\\index.php', 29)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\pesquisas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('pesquisas/index', [], true)
 5 APPPATH\Controllers\Pesquisas.php(22): view('pesquisas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pesquisas->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pesquisas))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-11 17:30:42 --> Undefined array key "id_user"
in APPPATH\Views\pesquisas\index.php on line 29.
 1 APPPATH\Views\pesquisas\index.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id_user"', 'C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\pesquisas\\index.php', 29)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\pesquisa_satisfacao\\app\\Views\\pesquisas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('pesquisas/index', [], true)
 5 APPPATH\Controllers\Pesquisas.php(22): view('pesquisas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pesquisas->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pesquisas))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
